/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ReasoningFactor = IDL.Record({
  'description' : IDL.Text,
  'factor' : IDL.Text,
});
export const Prediction = IDL.Record({
  'team1Probability' : IDL.Nat,
  'predictedWinner' : IDL.Text,
  'generatedAt' : Time,
  'team2Probability' : IDL.Nat,
  'reasoning' : IDL.Vec(ReasoningFactor),
  'matchId' : IDL.Text,
});
export const PredictionRecord = IDL.Record({
  'actualWinner' : IDL.Opt(IDL.Text),
  'predictedWinner' : IDL.Text,
  'date' : IDL.Text,
  'matchLabel' : IDL.Text,
  'isCorrect' : IDL.Opt(IDL.Bool),
  'matchId' : IDL.Text,
});
export const Stats = IDL.Record({
  'totalPredictions' : IDL.Nat,
  'correctPredictions' : IDL.Nat,
  'accuracy' : IDL.Nat,
});
export const Match = IDL.Record({
  'id' : IDL.Text,
  'actualWinner' : IDL.Opt(IDL.Text),
  'team1' : IDL.Text,
  'team2' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'venue' : IDL.Text,
  'matchDate' : Time,
});

export const idlService = IDL.Service({
  'getPrediction' : IDL.Func([IDL.Text], [IDL.Opt(Prediction)], []),
  'getPredictionHistory' : IDL.Func([], [IDL.Vec(PredictionRecord)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUpcomingMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'setActualWinner' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ReasoningFactor = IDL.Record({
    'description' : IDL.Text,
    'factor' : IDL.Text,
  });
  const Prediction = IDL.Record({
    'team1Probability' : IDL.Nat,
    'predictedWinner' : IDL.Text,
    'generatedAt' : Time,
    'team2Probability' : IDL.Nat,
    'reasoning' : IDL.Vec(ReasoningFactor),
    'matchId' : IDL.Text,
  });
  const PredictionRecord = IDL.Record({
    'actualWinner' : IDL.Opt(IDL.Text),
    'predictedWinner' : IDL.Text,
    'date' : IDL.Text,
    'matchLabel' : IDL.Text,
    'isCorrect' : IDL.Opt(IDL.Bool),
    'matchId' : IDL.Text,
  });
  const Stats = IDL.Record({
    'totalPredictions' : IDL.Nat,
    'correctPredictions' : IDL.Nat,
    'accuracy' : IDL.Nat,
  });
  const Match = IDL.Record({
    'id' : IDL.Text,
    'actualWinner' : IDL.Opt(IDL.Text),
    'team1' : IDL.Text,
    'team2' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'venue' : IDL.Text,
    'matchDate' : Time,
  });
  
  return IDL.Service({
    'getPrediction' : IDL.Func([IDL.Text], [IDL.Opt(Prediction)], []),
    'getPredictionHistory' : IDL.Func(
        [],
        [IDL.Vec(PredictionRecord)],
        ['query'],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUpcomingMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'setActualWinner' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };