/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Match {
  'id' : string,
  'actualWinner' : [] | [string],
  'team1' : string,
  'team2' : string,
  'isCompleted' : boolean,
  'venue' : string,
  'matchDate' : Time,
}
export interface Prediction {
  'team1Probability' : bigint,
  'predictedWinner' : string,
  'generatedAt' : Time,
  'team2Probability' : bigint,
  'reasoning' : Array<ReasoningFactor>,
  'matchId' : string,
}
export interface PredictionRecord {
  'actualWinner' : [] | [string],
  'predictedWinner' : string,
  'date' : string,
  'matchLabel' : string,
  'isCorrect' : [] | [boolean],
  'matchId' : string,
}
export interface ReasoningFactor { 'description' : string, 'factor' : string }
export interface Stats {
  'totalPredictions' : bigint,
  'correctPredictions' : bigint,
  'accuracy' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'getPrediction' : ActorMethod<[string], [] | [Prediction]>,
  'getPredictionHistory' : ActorMethod<[], Array<PredictionRecord>>,
  'getStats' : ActorMethod<[], Stats>,
  'getUpcomingMatches' : ActorMethod<[], Array<Match>>,
  'initialize' : ActorMethod<[], undefined>,
  'setActualWinner' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];